"""initial client_profiles table

Revision ID: 67fe14e57389
Revises: 
Create Date: 2025-06-18 11:33:57.493416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fe14e57389'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('has_sports_license', sa.Boolean(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_smoker', sa.Boolean(), nullable=True),
    sa.Column('is_french_national', sa.Boolean(), nullable=True),
    sa.Column('estimated_monthly_income', sa.Float(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('credit_history', sa.String(length=500), nullable=True),
    sa.Column('personal_risk_score', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Float(), nullable=True),
    sa.Column('loan_amount_requested', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_profiles')
    # ### end Alembic commands ###
