"""ajout colonnes orientation_sexuelle, nb_enfants, quotient_caf

Revision ID: 6ac219aa4276
Revises: 67fe14e57389
Create Date: 2025-06-18 11:36:03.237731

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ac219aa4276"
down_revision: Union[str, Sequence[str], None] = "67fe14e57389"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_profiles", sa.Column("nb_enfants", sa.Integer(), nullable=True)
    )
    op.add_column(
        "client_profiles", sa.Column("quotient_caf", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_profiles", "quotient_caf")
    op.drop_column("client_profiles", "nb_enfants")
    # ### end Alembic commands ###
